FaNgMvcBs2/Controllers/DrugEventController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using FdaService;
using FdaService.Models.Drug.Event;
using FaNgMvcBs2.ViewModels;
using System.Collections.Generic;


// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FaNgMvcBs2.Controllers
{
    public class DrugEventController : Controller
    {
        public IActionResult Index()
        {
            var drugEventViewModel = new DrugEventViewModel();
            drugEventViewModel.SearchCriteria = SearchLookups.GetResultFields().ToList();

            return View(drugEventViewModel);
        }
        [HttpPost]
        public IActionResult Index(DrugEventViewModel model)
        {
            var drugEventViewModel = new DrugEventViewModel();
            drugEventViewModel.SearchCriteria = SearchLookups.GetResultFields().ToList();

            drugEventViewModel.RootObject = ServiceHelper.GetData<RootObject>("https://api.fda.gov",
                "/drug/event.json?",
                string.Format("search={0}:\"{1}\"&limit=50", model.SearchCriteriaSelected, model.SearchInfo)); //"search=patient.drug.openfda.pharm_class_epc:\"nonsteroidal+anti-inflammatory+drug\"");
                                                                                                               //"search=patient.drug.openfda.brand_name:\"allegra\"&limit=50");

            //drugEventViewModel.RootObject.results = drugEventViewModel.RootObject.results.Take<Result>(5).ToList();
            return View(drugEventViewModel);
        }

        public IActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Search(DrugEventViewModel model)
        {
            if (!string.IsNullOrWhiteSpace(model.SearchInfo))
            {
                return Display(model);
            }
            else
            {
                return Search();
            }
        }

        public IActionResult Display(DrugEventViewModel model)
        {
            model.RootObject = ServiceHelper.GetData<RootObject>("https://api.fda.gov",
                "/drug/event.json?",
                string.Format("search={0}:\"{1}\"&limit=50", "patient.drug.openfda.brand_name", model.SearchInfo)); //"search=patient.drug.openfda.pharm_class_epc:\"nonsteroidal+anti-inflammatory+drug\"");
            model.Drugs = new List<FdaService.Models.Drug.Event.Drug>();
            model.Reactions = new List<Reaction>();

            if (model.RootObject != null && model.RootObject.results != null)
            {
                foreach (var result in model.RootObject.results)
                {
                    foreach (var drug in result.patient.drug)
                    {
                        if (!model.Drugs.Any(d => d.medicinalproduct == drug.medicinalproduct) && model.Drugs.Count < 100)
                        {
                            model.Drugs.Add(drug);
                        }
                    }
                    foreach (var reaction in result.patient.reaction)
                    {
                        if (!model.Reactions.Any(r => r.reactionmeddrapt == reaction.reactionmeddrapt) && model.Reactions.Count < 100)
                        {
                            model.Reactions.Add(reaction);
                        }
                    }
                }

                model.Drugs = model.Drugs.OrderBy(a => a.medicinalproduct).ToList();
                model.Reactions = model.Reactions.OrderBy(r => r.reactionmeddrapt).ToList();
            }
            return View("Display", model);
        }
    }
}

FaNgMvcBs2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using FdaService;
using FdaService.Models.Drug.Event;
using FaNgMvcBs2.ViewModels;

namespace FaNgMvcBs2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {


            return View();
        }


        public IActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

FaNgMvcBs2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FaNgMvcBs2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FaNgMvcBs2/Views/Home/Index.cshtml
@using FdaService.Models.Drug.Event
@using FaNgMvcBs2.ViewModels
@model DrugEventViewModel

@{
    ViewBag.Title = "MedFind - Home";
}


<!-- HP Hero -->
<div class="hero">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-8">
                <h1>
                    Take Control
                    <br /><strong>of Your</strong>
                    <br />Medical Care
                </h1>
                <p>Your FDA is here to support your care and help you make the best decisions for you and your family.</p>

                <div class="icon-row clearfix">
                    <a class="ico-fda pull-left hide-text" href="#"></a>
                    <a class="ico-bird pull-left hide-text" href="#"></a>
                </div>

                <div class="login-container clearfix">
                    <fieldset>
                        <div class="form-group">
                            @using (Html.BeginForm("Search", "DrugEvent", FormMethod.Post))
                            {
                                <label class="hide-label" for="SearchInfo">Find Medication</label>
                                @* TODO: find attributes to make this work --> Html.EditorFor(model => model.SearchInfo)*@
                                <input type="text" id="input-findDrugInfo" class="form-control" placeholder="Type in your drug here" />
                                <button type="submit" class="btn btn-primary">Go To My Drug Info</button>
                            }

                        </div>
                    </fieldset>
                </div>
                <!-- /login-container -->

            </div>
            <!-- /col -->

        </div>
        <!-- /row -->
        <div class="hero-img">

        </div>
        <div class="hero-img invisible-sm"></div>
    </div>
</div>
<!-- /container -->
    </div>
<!-- /hero -->

<div class="container hidden-xs">
    <div class="row">
        <div class="col-md-5 col-sm-8 col-xs-12">
            <div class="testimonial quote-1">
                <blockquote>&quot;Life moves fast! I don't always slow down to listen to my doctor.  I am so glad that I have MedFinder to research my properly medications when I have the time&quot;</blockquote>
            </div>
        </div>
        <div class="col-md-5 col-md-offset-1 col-sm-8 col-xs-12">
            <div class="testimonial quote-2">
                <blockquote>“I depend on MedFinder to understand how to manage my medications.  My pharmacist and doctor do advise me, but I like to own my own care plan.”</blockquote>
            </div>
        </div>
    </div>
</div>
<!-- /container -->

<div class="container visible-xs">
    <p class="testimonial-intro">See how Americans like you are using <br />MY DRUG REPORT to manage their care</p>
    <div class="row">
        <div class="col-md-5 col-xs-12">
            <div class="testimonial quote-3">
                <blockquote>
                    &quot;We depend on each other. 
                    It makes me feel better to do my own research about what my husband is  taking!&quot;
                </blockquote>
            </div>
        </div>
    </div>
</div>
<!-- /container -->